// <auto-generated />
using JT_webBurguer2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JT_webBurguer2.Migrations
{
    [DbContext(typeof(JT_webBurguer2Context))]
    [Migration("20241021154613_Inicio2")]
    partial class Inicio2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JT_webBurguer2.Models.Burguer", b =>
                {
                    b.Property<int>("BurguerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BurguerId"));

                    b.Property<string>("BurguerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("priceCeiling")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("withCheese")
                        .HasColumnType("bit");

                    b.HasKey("BurguerId");

                    b.ToTable("Burguer");
                });
#pragma warning restore 612, 618
        }
    }
}
